const option = (label, value, scores = {}) => ({ label, value, scores });

export const BUILD_QUESTIONS = Object.freeze([
  { id: "segment", prompt: "Qual é o seu segmento ou tipo de negócio?", type: "text", required: true },
  { id: "problem", prompt: "Qual problema você quer resolver?", type: "text", required: true },
  { id: "users", prompt: "Quem utilizará o aplicativo?", type: "single", required: true, options: [option("Meus clientes", "customers", { start: 1 }), option("Minha equipe", "team", { pro: 2 }), option("Clientes e equipe", "both", { business: 2 }), option("Muitos usuários", "many", { saas: 3 })] },
  { id: "goal", prompt: "Qual resultado seria mais importante?", type: "single", required: true, options: [option("Divulgar produtos e serviços", "showcase", { start: 3 }), option("Organizar atendimentos", "operations", { pro: 3 }), option("Automatizar a empresa", "automation", { business: 3 }), option("Vender uma assinatura", "recurring", { saas: 4 })] },
  { id: "essentials", prompt: "Quais funções são indispensáveis?", type: "multi", required: true, options: [option("Catálogo", "catalog", { start: 1 }), option("WhatsApp", "whatsapp", { start: 1 }), option("Login", "login", { pro: 2 }), option("Banco de dados", "database", { pro: 2 }), option("Painel administrativo", "admin", { pro: 2 }), option("Marketplace", "marketplace", { business: 4 }), option("Pagamentos recorrentes", "subscriptions", { saas: 5 }), option("Sistema financeiro", "finance", { business: 5 }), option("IA avançada", "advanced-ai", { business: 5 }), option("Integrações externas", "integrations", { business: 4 })] },
  { id: "existing", prompt: "Você já possui site, sistema ou aplicativo?", type: "single", required: true, options: [option("Ainda não", "none"), option("Tenho um site", "site", { start: 1 }), option("Tenho um sistema", "system", { pro: 1 }), option("Tenho um aplicativo", "app", { business: 1 })] },
  { id: "start", prompt: "Em quanto tempo pretende começar?", type: "single", required: true, options: [option("Agora", "now"), option("Em até 30 dias", "30-days"), option("Em até 90 dias", "90-days"), option("Estou pesquisando", "researching")] },
  { id: "investment", prompt: "Qual faixa de investimento considera?", type: "single", required: true, options: [option("Até R$ 600", "starter", { start: 2 }), option("Até R$ 1.500", "pro", { pro: 2 }), option("Até R$ 3.000", "business", { business: 2 }), option("Acima de R$ 5.000", "saas", { saas: 2 }), option("Ainda não sei", "unknown")] },
  { id: "solution", prompt: "Qual formato parece mais adequado?", type: "single", required: true, options: [option("Solução rápida adaptada ao meu nicho", "ready", { start: 2 }), option("Aplicativo personalizado", "custom", { pro: 2 }), option("Sistema completo", "complete", { business: 3 }), option("Plataforma por assinatura", "platform", { saas: 4 }), option("Preciso de orientação", "unknown")] },
]);
export const LEARN_QUESTIONS = Object.freeze([
  { id: "level", prompt: "Qual é o seu nível atual?", type: "single", required: true, options: [option("Estou começando do zero", "beginner", { "learn-entry": 3 }), option("Já conheço algumas ferramentas", "basic", { "learn-entry": 2 }), option("Já criei projetos", "intermediate", { "learn-mentoring": 2 })] },
  { id: "builtBefore", prompt: "Você já criou algum aplicativo?", type: "single", required: true, options: [option("Não", "no", { "learn-entry": 2 }), option("Comecei, mas não terminei", "unfinished", { "learn-entry": 1 }), option("Sim", "yes", { "learn-mentoring": 2 })] },
  { id: "objective", prompt: "O que deseja construir primeiro?", type: "single", required: true, options: [option("Meu primeiro aplicativo", "first-app", { "learn-entry": 3 }), option("Um aplicativo para minha empresa", "business-app", { "learn-entry": 2 }), option("Um produto para vender", "product", { "learn-mentoring": 2 }), option("Aplicativos para clientes", "client-apps", { "learn-mentoring": 3 })] },
  { id: "incomeGoal", prompt: "Qual é o seu objetivo principal?", type: "single", required: true, options: [option("Uso próprio", "own-use", { "learn-entry": 2 }), option("Nova carreira", "career", { "learn-mentoring": 2 }), option("Renda extra", "extra-income", { "learn-mentoring": 2 }), option("Criar uma empresa", "company", { "learn-mentoring": 3 })] },
  { id: "weeklyTime", prompt: "Quanto tempo por semana pode estudar?", type: "single", required: true, options: [option("Até 2 horas", "under-2"), option("De 2 a 4 horas", "2-4"), option("De 5 a 8 horas", "5-8"), option("Mais de 8 horas", "over-8")] },
  { id: "format", prompt: "Como você prefere aprender?", type: "single", required: true, options: [option("Aulas gravadas", "lessons", { "learn-entry": 2 }), option("Projeto prático", "project", { "learn-entry": 1 }), option("Acompanhamento", "support", { "learn-mentoring": 3 }), option("Mentoria individual", "mentoring", { "learn-mentoring": 4 })] },
  { id: "tools", prompt: "Quais ferramentas você já utiliza?", type: "multi", required: false, options: [option("ChatGPT", "chatgpt"), option("GitHub", "github"), option("Supabase", "supabase"), option("Vercel", "vercel"), option("Nenhuma", "none")] },
  { id: "sellApps", prompt: "Você pretende vender aplicativos para clientes?", type: "single", required: true, options: [option("Não agora", "no", { "learn-entry": 1 }), option("Talvez no futuro", "maybe", { "learn-entry": 1 }), option("Sim", "yes", { "learn-mentoring": 3 })] },
  { id: "start", prompt: "Quando deseja começar?", type: "single", required: true, options: [option("Agora", "now"), option("Este mês", "month"), option("Nos próximos 3 meses", "quarter"), option("Estou pesquisando", "researching")] },
]);
