import { BUILD_QUESTIONS, LEARN_QUESTIONS } from "./questions.js";
export function isPublishableNumber(value) { return /^55\d{10,11}$/.test(String(value || "").replace(/\D/g, "")); }
const FIELD_LABELS = {
  build: { goal:"O que deseja criar", stage:"Etapa atual", solution:"Solução desejada" },
  learn: { builtBefore:"Experiência atual", objective:"O que quer criar", start:"Quando quer começar" },
};
function routeQuestions(route){return route==="build"?BUILD_QUESTIONS:LEARN_QUESTIONS;}
function displayValue(question,raw){if(raw==null||raw==="")return"";if(question?.type==="text")return String(raw);const values=Array.isArray(raw)?raw:[raw];return values.map(value=>question?.options?.find(item=>item.value===value)?.label||String(value)).join(", ");}
function displayOrigin(utm={}){const sourceMap={ig:"Instagram",instagram:"Instagram",facebook:"Facebook",fb:"Facebook",whatsapp:"WhatsApp",direct:"Acesso direto"};const contentMap={link_in_bio:"Link na bio",bio:"Link na bio",story:"Story",stories:"Stories",reel:"Reel"};const source=sourceMap[String(utm.source||"").toLowerCase()]||utm.source||"";const content=contentMap[String(utm.content||"").toLowerCase()]||utm.content||"";return[source,content].filter(Boolean).join(" / ");}
export function buildWhatsAppMessage(session,recommendation){const route=session.route==="build"?"build":"learn";const intent=route==="build"?"quero criar um aplicativo":"quero aprender a criar aplicativos";const recommendationText=recommendation.priceLabel?`${recommendation.title} — ${recommendation.priceLabel}`:recommendation.title;const rows=[`Olá, Raphael. Fiz o Diagnóstico AUREON e ${intent}.`,"","*Dados do diagnóstico*",`Nome: ${session.identity?.name||"Não informado"}`,`Recomendação: ${recommendationText}`,"","*Resumo*"];const questions=routeQuestions(route);const labels=FIELD_LABELS[route];for(const question of questions){const raw=session.answers?.[question.id];const value=displayValue(question,raw);if(value)rows.push(`• ${labels[question.id]||question.prompt}: ${value}`);}const origin=displayOrigin(session.utm);if(origin)rows.push("",`Origem: ${origin}`);rows.push("","Quero saber qual é o próximo passo.");return rows.join("\n");}
export function buildWhatsAppUrl(number,message){const digits=String(number||"").replace(/\D/g,"");if(!isPublishableNumber(digits))throw new Error("Número comercial da AUREON inválido");return`https://wa.me/${digits}?text=${encodeURIComponent(message)}`;}
